### ISSUE TITLE
Unhandled Promise Rejection for 'ctra --help'

### ISSUE THREAD

**Issue by mathiasmah** [CantaraJS/cantara#12]
When command 'ctra --help' is executed the following error occurs: 

> (node:11092) UnhandledPromiseRejectionWarning: Error: You must specify an action, e.g.: cantara e2e
    at Object.<anonymous> (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\cli\cli-tools\index.js:103:31)
    at step (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\cli\cli-tools\index.js:44:23)
    at Object.next (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\cli\cli-tools\index.js:25:53)
    at C:\applications\nvm\v12.13.0\node_modules\cantara\dist\cli\cli-tools\index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\cli\cli-tools\index.js:15:12)
    at Object.execCantaraCommand (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\cli\cli-tools\index.js:97:12)
    at Object.setupCliInterface [as default] (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\cli\index.js:175:24)
    at main (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\index.js:9:18)
    at Object.<anonymous> (C:\applications\nvm\v12.13.0\node_modules\cantara\dist\index.js:11:1)
(node:11092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by scriptify** [comment]
Will be fixed with #5 

There is currently no --help command 😬
