### ISSUE TITLE
Add a nice "Usage" response when starting cantara without arguments

### ISSUE THREAD

**Issue by mrxder** [CantaraJS/cantara#28]
To improve user experience cantara should print a nice help/usage section to the terminal.
instead of:
`
cantara
Error: You must specify an action, e.g.: cantara e2e
    at Object.<anonymous> (/usr/local/lib/node_modules/cantara/dist/cli/cli-tools/index.js:104:31)
    at step (/usr/local/lib/node_modules/cantara/dist/cli/cli-tools/index.js:44:23)
    at Object.next (/usr/local/lib/node_modules/cantara/dist/cli/cli-tools/index.js:25:53)
`

something like this:
`
Usage: node [options] [ -e script | script.js | - ] [arguments]
       node inspect script.js [arguments]
`

**Comment by scriptify** [comment]
Will be fixed with #5 
When using something like CommanderJS this will work out of the box. Will close this issue in favor of that one
